services:
  - type: web
    name: SHIRAH-AI
    env: node
    plan: free
    repo: https://github.com/Maxtech24/SHIRAH-AI
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
